"attribute" = { fg = "light-black" }

"comment" = { "fg" = "gray", modifiers = ["italic"] }
"comment.block" = { fg = "gray", modifiers = ["italic"] }
"comment.block.documentation" = { fg = "light-green", modifiers = ["italic"] }
"comment.line" = { fg = "gray", modifiers = ["italic"] }

"constant" = { fg = "light-yellow" }
"constant.builtin" = { fg = "light-yellow" }
"constant.character.escape" = { fg = "light-yellow" }
"constant.numeric" = { fg = "light-yellow" }

"constructor" = { fg = "white" }

"diagnostic" = { underline.style = "line" }

"diff.minus" = { fg = "red" }
"diff.plus" = { fg = "green" }
"diff.delta.moved" = { fg = "yellow" }
"diff.delta.conflict" = { fg = "purple" }

"error" = { fg = "red", modifiers = ["bold"] }

"function" = { fg = "light-yellow" }
"function.builtin" = { fg = "light-blue" }
"function.macro" = { fg = "light-purple" }

"hint" = { fg = "green", modifiers = ["bold"] }

"info" = { fg = "blue", modifiers = ["bold"] }

"keyword" = { fg = "light-blue" }
"keyword.operator" = { fg = "white" }
"keyword.storage.modifier" = { fg = "yellow" }

"label" = { fg = "light-green" }

"markup.bold" = { fg = "yellow", modifiers = ["bold"] }
"markup.heading" = { fg = "red" }
"markup.italic" = { fg = "purple", modifiers = ["italic"] }
"markup.link.label" = { fg = "white" }
"markup.link.text" = { fg = "white" }
"markup.link.url" = { fg = "blue", underline.style = "line" }
"markup.list" = { fg = "red" }
"markup.quote" = { fg = "yellow" }
"markup.raw.block" = { fg = "white" }
"markup.raw.inline" = { fg = "green" }

"namespace" = { fg = "light-cyan" }

"operator" = { fg = "white" }

"punctuation" = { fg = "white" }
"punctuation.special" = { fg = "gray" }

"special" = { fg = "light-blue" }

"string" = { fg = "light-green" }

"type" = { fg = "yellow" }

"type.builtin" = { fg = "light-red" }

"ui.background" = {}

"ui.cursor" = { fg = "white", modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "blue", underline.style = "line" }
"ui.cursor.primary" = { fg = "white", modifiers = ["reversed"] }

"ui.cursorline.primary" = { fg = "yellow", underline = { color = "yellow",  style = "double_line" } }
"ui.cursorline.secondary" = { underline = { color = "yellow", style = "line" } }

"ui.help" = { fg = "white", bg = "background" }

"ui.linenr" = { fg = "black" }
"ui.linenr.selected" = { fg = "yellow" }

"ui.menu" = { fg = "white" }
"ui.menu.scroll" = { fg = "light-red", bg = "background" }
"ui.menu.selected" = { fg = "light-red", bg = "background" }

"ui.popup" = { bg = "background" }

"ui.selection" = { bg = "light-black" }
"ui.selection.primary" = { bg = "light-black" }

"ui.statusline" = { fg = "white" }
"ui.statusline.inactive" = { fg = "black" }
"ui.statusline.insert" = { fg = "light-green" }
"ui.statusline.normal" = { fg = "light-purple" }
"ui.statusline.select" = { fg = "light-cyan" }

"ui.text" = { fg = "white" }

"ui.text.focus" = { fg = "white", bg = "light-black", modifiers = ["bold"] }

"ui.virtual" = { fg = "gray" }
"ui.virtual.indent-guide" = { fg = "gray" }
"ui.virtual.ruler" = { bg = "black" }
"ui.virtual.whitespace" = { fg = "light-black" }

"ui.window" = { fg = "background" }

"variable" = { fg = "white" }
"variable.builtin" = { fg = "light-red" }
"variable.other.member" = { fg = "white" }
"variable.parameter" = { fg = "white" }

"warning" = { fg = "yellow", modifiers = ["bold"] }

[palette]
background = "#1c1c1c"
black = "#282A2E"
blue = "#5F819D"
cyan = "#5E8D87"
gray = "#707880"
green = "#8C9440"
light-black = "#373B41"
light-blue = "#81A2BE"
light-cyan = "#8ABEB7"
light-gray = "#C5C8C6"
light-green = "#B5BD68"
light-purple = "#B294BB"
light-red = "#CC6666"
light-yellow = "#F0C674"
purple = "#85678F"
red = "#A54242"
white = "#C5C8C6"
yellow = "#DE935F"

