#!/bin/bash

# Navigate to root of yadm repository.
cd "$HOME"

# Set up submodules.
echo ":: Initialize submodules..."
yadm submodules update --recursive --init

# Install Vundle plugins.
if command -v vim >/dev/null 2>&1; then
	echo ":: Install Vim Plugins..."
	vim '+PluginInstall' '+qall'
fi

# Install tpm plugins.
$HOME/.tmux/plugins/tpm/bin/install_plugins

# Reload the bash configuration.
source "$HOME/.bashrc"
