#!/bin/bash

# Navigate to root of yadm repository.
cd "$HOME"

# Set up submodules.
echo ":: Initialize submodules..."
yadm submodule update --recursive --init

# Install fzf
$HOME/.fzf/install --all

# Adjust file permissions.
chmod +x ~/.yadm/external/rfc/rfc

# Make our symlinks.
echo ":: Creating symlinks..."
mkdir -p ~/.local/bin
ln -s ~/.yadm/external/rfc/rfc ~/.local/bin/rfc
chmod -R 700 ~/.local/bin
ln -s ~/.yadm/external/gdb-dashboard/.gdbinit ~/.gdbinit

# Make other directories.
mkdir -p ~/.go

# Create .Xdefaults
ln -s ~/.Xresources ~/.Xdefaults

# Making yadm cache directories.
echo ":: Creating cache for fasd..."
mkdir -p ~/.zsh/cache/
touch ~/.zsh/cache/fasd-init-cache
touch ~/.fasd-init-bash

# Making Vim backup directories.
echo ":: Creating directories for Vim..."
mkdir -p ~/.vim/backup
mkdir -p ~/.vim/undo

# Install vim-plug plugins.
if command -v vim >/dev/null 2>&1; then
    echo ":: Install Vim plugins..."
    vim '+PackUpdate' '+qall'
fi

# Ensure we don't have a wide open executable directory.
chmod -R 700 ~/.fzf

# Install tpm plugins.
echo ":: Install tmux plugins..."
$HOME/.tmux/plugins/tpm/bin/install_plugins

# Reload the bash configuration.
echo ":: Reloading .bashrc"
source "$HOME/.bashrc"

# Install Antibody for zsh.
if ! command -v antibody >/dev/null 2>&1; then
    if command -v brew >/dev/null 2>&1; then
        brew install getantibody/tap/antibody || brew upgrade antibody
    else
        curl -sL https://git.io/antibody | sh -s
    fi
fi

# Update and install plugins.
antibody bundle < "$HOME/.antibody_bundle" > "$HOME/.zsh_plugins.sh"
